Mixing_Type:           anderson
Mixing_MaxDim:         14
Mixing_Variable:       potential
Mixing_StepLength:     0.4
Extra_States:          0
Temperature:           0.1
SCF_Outer_MaxIter:     1000
DFT_SCF_Outer_MaxIter: 1000


SCF_Outer_Tolerance:   1e-6
SCF_Inner_MaxIter:     1
SCF_Inner_Tolerance:   1e-6
Eig_MaxIter:           2
Eig_Tolerance:         1e-20

SVD_Basis_Tolerance:   1e-20
Use_Atom_Density:    0
Pseudo_Type:           ONCV
##XC_Type:               XC_GGA_XC_PBE

UPF_File:
  -  C_ONCV_PBE-1.0.upf
  -  H_ONCV_PBE-1.0.upf

Use_VLocal:            1
Penalty_Alpha:         20.0

PW_Solver:             LOBPCG
#ScaLAPACK_Block_Size:  32

Density_Grid_Factor:   1.0
#LGL_Grid_Factor:       2.0

#Geo_Opt_Max_Step:      400

#Calculate_Force_Each_SCF:    0


#Solution_Method:      diag

Diag_SCFDG_by_Cheby:           0 
SCFDG_Cheby_use_ScaLAPACK:      0
First_SCFDG_ChebyFilterOrder:   2
First_SCFDG_ChebyCycleNum:      3
Second_SCFDG_ChebyOuterIter:    1
Second_SCFDG_ChebyFilterOrder:  3
Second_SCFDG_ChebyCycleNum:     1
General_SCFDG_ChebyFilterOrder: 3
General_SCFDG_ChebyCycleNum:    1


Solution_Method:      diag



Ecut_Wavefunction:     10
ALB_Num:               128

Element_Size: [1, 3, 3]

Atom_Types_Num:        2

Atom_Type: [ 6 , 1] # O,  Al, Ti, Sr, La

Atom_Num:  [ 6 , 6]
Super_Cell: [ 19.9933013916 ,  19.9933013916 ,  19.9933013916 ]

Atom_Red:

-   [  0.367730021   ,      0.500000000    ,      0.500000000 ]
-   [   0.433889985  ,       0.385490000   ,      0.500000000 ]
-   [   0.566110015  ,       0.385490000   ,      0.500000000 ]
-   [   0.632269979  ,       0.500000000   ,      0.500000000 ]
-   [   0.566110015  ,       0.614510000   ,      0.500000000 ]
-   [   0.433889985  ,       0.614510000   ,      0.500000000 ]
-   [   0.264559984  ,       0.500000000   ,      0.500000000 ]
-   [   0.382310033  ,       0.296149969   ,      0.500000000 ]
-   [   0.617689967  ,       0.296149969   ,      0.500000000 ]
-   [   0.735440016  ,       0.500000000   ,      0.500000000 ]
-   [   0.617689967  ,       0.703850031   ,      0.500000000 ]
-   [   0.382310033  ,       0.703850031   ,      0.500000000 ]

